# Generated by Django 6.0 on 2025-12-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_technician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_package',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vehicle',
        ),
    ]
