# Generated by Django 6.0 on 2025-12-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_address_booking_created_at_booking_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='chemical_recipe',
            field=models.JSONField(default=dict, help_text="Dictionary of chemical names and amounts (e.g. {'soap': 0.5})"),
        ),
    ]
