# Generated by Django 6.0 on 2025-12-13 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_servicepackage_chemical_recipe'),
        ('finance', '0002_chemicalinventory_commissionrule_expensecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='commission_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.commissionrule'),
        ),
    ]
