# Generated by Django 6.0 on 2025-12-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_servicepackage_commission_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='points_redeemed',
            field=models.IntegerField(default=0),
        ),
    ]
