# Generated by Django 6.0 on 2026-03-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_points_redeemed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bay_assignment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('WAITING', 'Waiting'), ('IN_BAY_1', 'In Bay 1'), ('IN_BAY_2', 'In Bay 2'), ('DETAILING', 'Detailing'), ('READY', 'Ready for Pickup'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20),
        ),
    ]
