# Generated by Django 6.0 on 2026-09-09 17:56

import django.db.models.deletion
from django.db import migrations, models


def populate_default_tiered_prices(apps, schema_editor):
    ServicePackage = apps.get_model('bookings', 'ServicePackage')
    ServicePackagePrice = apps.get_model('bookings', 'ServicePackagePrice')
    
    STANDARD_TYPES = ['HATCHBACK', 'SEDAN', 'COMPACT_SUV', 'SUV', 'MUV', 'BIKE', 'LUXURY']
    
    for pkg in ServicePackage.objects.all():
        for v_type in STANDARD_TYPES:
            ServicePackagePrice.objects.get_or_create(
                package=pkg,
                vehicle_type=v_type,
                defaults={'price': pkg.price or 0.00}
            )

class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_base_price_booking_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackage',
            name='vehicle_type',
            field=models.CharField(choices=[('ALL', 'All Vehicle Types'), ('HATCHBACK', 'Hatchback'), ('SEDAN', 'Sedan'), ('COMPACT_SUV', 'Compact SUV'), ('SUV', 'Full SUV'), ('MUV', 'MUV'), ('BIKE', 'Bike'), ('VAN', 'Van'), ('LUXURY', 'Luxury'), ('AUTO', 'Auto'), ('TRUCK', 'Truck')], db_index=True, default='ALL', max_length=20),
        ),
        migrations.CreateModel(
            name='ServicePackagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('ALL', 'All Vehicle Types'), ('HATCHBACK', 'Hatchback'), ('SEDAN', 'Sedan'), ('COMPACT_SUV', 'Compact SUV'), ('SUV', 'Full SUV'), ('MUV', 'MUV'), ('BIKE', 'Bike'), ('VAN', 'Van'), ('LUXURY', 'Luxury'), ('AUTO', 'Auto'), ('TRUCK', 'Truck')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiered_prices', to='bookings.servicepackage')),
            ],
            options={
                'unique_together': {('package', 'vehicle_type')},
            },
        ),
        migrations.RunPython(populate_default_tiered_prices, migrations.RunPython.noop),
    ]
