# Generated by Django 6.0 on 2026-09-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('bookings', '0005_booking_address_booking_created_at_booking_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='type',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], default='WHATSAPP', max_length=10),
        ),
    ]
