with open('kallayi_car_spa_frontend/src/app/(admin)/admin/dashboard/page.tsx', 'r', encoding='utf-8') as f:
    lines = f.readlines()

end_header_idx = 0
for i, l in enumerate(lines):
    if l.startswith('export default function AdminDashboard()'):
        end_header_idx = i
        break

end_logic_idx = 0
for i, l in enumerate(lines):
    if 'if (isLoading) return' in l:
        end_logic_idx = i
        break

imports = "".join(lines[:end_header_idx])
# Filter out "use client" if it's there, but we'll prepend it anyway
logic = "".join(lines[end_header_idx+1:end_logic_idx])

context_template = f"""{imports}
import {{ createContext, useContext, ReactNode }} from 'react';

const DashboardContext = createContext<any>(null);

export function DashboardProvider({{ children }}: {{ children: ReactNode }}) {{
{logic}
    const value = {{
        uiState: {{
            isLoading, setIsLoading, activeTab, setActiveTab, financeSubTab, setFinanceSubTab,
            staffSubTab, setStaffSubTab, adminName, setAdminName,
            isKhataModalOpen, setIsKhataModalOpen, isKhataCustomerModalOpen, setIsKhataCustomerModalOpen,
            isKhataLedgerModalOpen, setIsKhataLedgerModalOpen, isManualKhataOpen, setIsManualKhataOpen,
            isServiceModalOpen, setIsServiceModalOpen, isStaffModalOpen, setIsStaffModalOpen,
            isAdvanceModalOpen, setIsAdvanceModalOpen, isLedgerModalOpen, setIsLedgerModalOpen
        }},
        financeState: {{
            kpiData, chartData, expenses, expenseCategories, isSubmittingExpense, expenseForm,
            receiptFile, receiptPreview, editingExpense, khataCustomers, khataLedger, selectedKhataCustomer,
            editingKhataCustomer, khataCustomerForm, khataPaymentAmount, eodData, manualKhataForm,
            customerCredits, invoiceList, analyticsData, totalOutstandingCredit, totalDailyPayout,
            setExpenseForm, setReceiptFile, setReceiptPreview, setKhataCustomerForm, setKhataPaymentAmount, setManualKhataForm,
            fetchExpenseCategories, handleFileChange, clearFile, handleExpenseSubmit, startEditingExpense,
            cancelEditingExpense, deleteExpense, downloadTaxReport, downloadInvoice, approveExpense, settleCredit,
            openKhataCustomerModal, saveKhataCustomer, deleteKhataCustomer, loadKhataLedger, handleKhataSettle,
            handleCloseRegister, submitManualKhataCharge
        }},
        staffState: {{
            payrollData, staffDirectory, editingStaff, staffForm, advanceForm, setStaffForm, setAdvanceForm,
            fetchStaffDirectory, openStaffModal, saveStaff, terminateStaff, settleWorkerPay, handleAddAdvance
        }},
        serviceState: {{
            services, editingService, serviceForm, setServiceForm, fetchServices, openServiceModal, saveService, deleteService
        }},
        crmState: {{
            searchQuery, setSearchQuery, vehicleData, crmLoading, crmError, globalHistory, globalHistoryDate,
            setGlobalHistoryDate, editingLedgerEntry, setEditingLedgerEntry, ledgerForm, setLedgerForm,
            fetchGlobalHistory, updateLedgerEntry, deleteLedgerEntry, handleCrmSearch
        }},
        globalActions: {{
            fetchDashboardData, handleLogout
        }},
        queueState: {{
            recentBookings
        }}
    }};

    return (
        <DashboardContext.Provider value={{value}}>
            {{children}}
        </DashboardContext.Provider>
    );
}}

export function useDashboard() {{
    const context = useContext(DashboardContext);
    if (!context) {{
        throw new Error('useDashboard must be used within a DashboardProvider');
    }}
    return context;
}}
"""

# Replace "import React, { useEffect" with "import React, { createContext, useContext, ReactNode, useEffect"
# in the imports section, but imports already has it. We will just add it below. Wait, ReactNode isn't in 'react' if not imported.
# It doesn't hurt if we import it twice or just use React.ReactNode. Let's adjust:

context_template = context_template.replace("import { createContext, useContext, ReactNode } from 'react';", "import { createContext, useContext } from 'react';\ntype ReactNode = React.ReactNode;")


with open('kallayi_car_spa_frontend/src/components/admin/dashboard/context/DashboardContext.tsx', 'w', encoding='utf-8') as f:
    f.write(context_template)

print("Done writing Context generated by python")
