# Generated by Django 6.0.3 on 2026-07-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customervehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('AUTO', 'Auto'), ('VAN', 'Van'), ('TRUCK', 'Truck')], default='CAR', max_length=10),
        ),
    ]
