# Generated by Django 6.0.3 on 2026-07-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customervehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervehicle',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customervehicle',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
