# Generated by Django 6.0 on 2026-09-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customervehicle_color_customervehicle_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customervehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('HATCHBACK', 'Hatchback'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('BIKE', 'Bike'), ('VAN', 'Van'), ('LUXURY', 'Luxury'), ('CAR', 'Car'), ('AUTO', 'Auto'), ('TRUCK', 'Truck')], default='CAR', max_length=10),
        ),
    ]
