# Generated by Django 6.0 on 2025-12-13 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_servicepackage_chemical_recipe'),
        ('customers', '0002_subscriptionplan_fleetaccount_membersubscription'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_volume', models.DecimalField(decimal_places=2, help_text='Current volume in UOM', max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uom', models.CharField(default='oz', max_length=20)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of service price (0-100)', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_deferred',
            field=models.BooleanField(default=False, help_text='If true, this income is amortized over time (e.g. Subs)'),
        ),
        migrations.CreateModel(
            name='ChemicalUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.chemicalinventory')),
            ],
        ),
        migrations.CreateModel(
            name='DeferredRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('daily_amortization_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='revenue_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.revenuecategory'),
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('base_wage', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tips_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('staff_user', 'date')},
            },
        ),
    ]
