# Generated by Django 6.0 on 2025-12-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_generalexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalexpense',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
