# Generated by Django 6.0 on 2026-03-14 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_points_redeemed'),
        ('customers', '0004_customer_credit_limit_customer_outstanding_balance'),
        ('finance', '0005_generalexpense_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhataLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('CHARGE', 'Charge to Khata'), ('SETTLEMENT', 'Settlement Payment')], max_length=15)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khata_entries', to='customers.customer')),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khata_charges', to='bookings.booking')),
            ],
        ),
    ]
