# Generated by Django 6.0 on 2026-03-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_dailyregisteraudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='split_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='split_khata',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='split_online',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('ONLINE', 'Online'), ('SPLIT', 'Split Payment')], max_length=10, null=True),
        ),
    ]
