# Generated by Django 6.0.3 on 2026-04-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_invoice_split_cash_invoice_split_khata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
