# Generated by Django 6.0.3 on 2026-07-22 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_payrollentry_is_settled_payrollentry_settled_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generalexpense',
            name='expense_type',
            field=models.CharField(choices=[('BUSINESS', 'Business Expense'), ('STAFF', 'Staff Expense')], default='BUSINESS', max_length=10),
        ),
        migrations.AddField(
            model_name='generalexpense',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generalexpense',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generalexpense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card'), ('CHEQUE', 'Cheque')], default='CASH', max_length=15),
        ),
        migrations.AddField(
            model_name='generalexpense',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalexpense',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('ADVANCE', 'Advance'), ('DEDUCTION', 'Deduction'), ('BONUS', 'Bonus'), ('REIMBURSEMENT', 'Reimbursement'), ('INCENTIVE', 'Incentive')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='generalexpense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='generalexpense',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='APPROVED', max_length=10),
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('calculated_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card'), ('CHEQUE', 'Cheque')], default='CASH', max_length=15)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments_created', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
