# Generated by Django on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_collectionbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='khataledger',
            name='number_plate_image',
            field=models.ImageField(blank=True, null=True, upload_to='khata_proofs/'),
        ),
    ]
