# Generated by Django 6.0 on 2026-09-09 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_khataledger_number_plate_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalexpense',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RemoveField(
            model_name='generalexpense',
            name='is_active',
        ),
        migrations.AddField(
            model_name='invoice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='expense_type',
            field=models.CharField(choices=[('BUSINESS', 'Business Expense'), ('STAFF', 'Staff Expense')], db_index=True, default='BUSINESS', max_length=10),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='APPROVED', max_length=10),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('ADVANCE', 'Advance'), ('DEDUCTION', 'Deduction'), ('BONUS', 'Bonus'), ('REIMBURSEMENT', 'Reimbursement'), ('INCENTIVE', 'Incentive')], db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='payment_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
