# Generated by Django 6.0 on 2026-09-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_generalexpense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
