# Generated by Django 6.0 on 2025-12-13 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0007_servicepackage_commission_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOPChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('items', models.JSONField(default=list, help_text="List of string tasks e.g. ['Vacuum', 'Wax']")),
                ('service_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sop_checklists', to='bookings.servicepackage')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('WASHER', 'Washer'), ('MANAGER', 'Manager'), ('ADMIN', 'Owner/Admin')], default='WASHER', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_app_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_data', models.JSONField(default=dict, help_text='Key-value pairs of Item: Boolean')),
                ('photo_proof', models.ImageField(blank=True, null=True, upload_to='inspections/')),
                ('passed', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='bookings.booking')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_time', models.DateTimeField()),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('clock_in_location', models.CharField(blank=True, help_text='Lat,Long coordinates', max_length=100)),
                ('clock_out_location', models.CharField(blank=True, help_text='Lat,Long coordinates', max_length=100)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='staff.staffprofile')),
            ],
        ),
    ]
