# Generated by Django 6.0 on 2026-03-29 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffprofile_base_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
