# Generated by Django 6.0.3 on 2026-07-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staffprofile_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='salary_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='salary_type',
            field=models.CharField(choices=[('DAILY', 'Daily Salary'), ('MONTHLY', 'Monthly Salary'), ('COMMISSION', 'Commission Based'), ('CUSTOM', 'Custom Pay')], default='COMMISSION', max_length=20),
        ),
    ]
