# Generated by Django 6.0 on 2026-08-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffprofile_salary_amount_staffprofile_salary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed commission amount per service', max_digits=10),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='commission_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage Based'), ('FIXED', 'Fixed Amount Per Service')], default='PERCENTAGE', max_length=15),
        ),
    ]
